### PR TITLE
add ios and android as standard values for OSFamily

### PR DESCRIPTION
**Pull request by buchgr**

### CODE REVIEW

**Comment by buchgr** [comment]
@juergbi @edbaunton @EdSchouten

**Comment by juergbi** [comment]
Shouldn't we use `OSFamily` `linux` for Android and then distinguish between Android and other Linux distributions/variants by a new property such as `OSDistribution`?

A similar approach may or may not make sense for macOS/iOS. I'm not familiar enough with the commonalities and differences (besides the ISA).

**Comment by buchgr** [comment]
I wouldn't consider Android a Linux distribution. My intention was for `android` to indicate the worker running the action on an android device (i.e. a phone).

**Comment by sstriker** [comment]
We should drive this to closure.  @juergbi, does @buchgr 's comment address your question/concern?

**Comment by juergbi** [comment]
> I wouldn't consider Android a Linux distribution. My intention was for `android` to indicate the worker running the action on an android device (i.e. a phone).

If Android is not considered a Linux distribution, it's not clear to me which systems should and which shouldn't use `OSFamily` `linux`. Actions with input roots that only depend on the Linux kernel syscall interface should work in any case. And if the action depends on specific userspace libraries, tools, or services, `OSFamily` alone is anyway not specific enough (whether Android is considered a separate `OSFamily` or not). I.e., `OSFamily` `linux` alone should not indicate that it's a glibc-based environment.

Using `OSDistribution` `android` also matches the withdrawn proposal [Platforms for Bazel Remote Execution](https://docs.google.com/document/d/1VemwPeyZh2rRkTGVFV18TQbyxB3FPc9iTZKpshLpNGU/edit#).

Do you have an alternative suggestion how to define `OSFamily` `linux`?

**Comment by bergsieker** [comment]
@buchgr Any further thoughts here?

**Comment by bergsieker** [comment]
It seems that no one cares enough about this to drive it forward in 6+ months, and we didn't have agreement on what we should do. Closing for now. If someone submits an alternative proposal we can consider that separately.

**Pull request closed without merging**
