### PR TITLE
update rules_go

### PR DESCRIPTION
**Pull request by atetubou**
This is to use protobuf v2 library for Go.

### CODE REVIEW

**Comment by atetubou** [comment]
cc @EricBurnett

**Comment by EdSchouten** [comment]
Could we also use this occasion to migrate to Gazelle’s new way of naming targets? We still declare some go_default_library targets.

**Comment by atetubou** [comment]
Which way are you supposed to migrate? I currently feel that there is no established way to handle generated *.pb.go for bazel.

Also I'd like to focus only to update bazel rules in this PR.

**Comment by atetubou** [comment]
Thanks, but we use this via https://github.com/bazelbuild/remote-apis-sdks. So it is better to have *.pb.go eventually there?

**Pull request merged**
