### PR TITLE
Add bazel-remote to server implementations in README.md

### PR DESCRIPTION
**Pull request by mostynb**

### CODE REVIEW

**Review by EdSchouten — APPROVED** [review]

**Review by bergsieker — APPROVED** [review]

**Comment by bergsieker** [comment]
@buchgr Would you like for bazel-remote to be included here?

**Comment by mostynb** [comment]
@bergsieker I'm not sure how closely Jakob monitors github notifications these days, but I doubt he would object to this. He handed over maintainership of bazel-remote to me around the end of 2019.

**Comment by bergsieker** [comment]
Ah, thanks. I wasn't aware that ownership had changed.

**Comment by buchgr** [comment]
Yep, +1 to all that @mostynb said :-).

**Pull request merged**
