### PR TITLE
Readme - add Scoot to server implementation links

### PR DESCRIPTION
**Pull request by dgassaway**

### CODE REVIEW

**Comment by dgassaway** [comment]
I signed it!

**Comment by finnball** [comment]
Welcome :)

Are you guys planning on having a slack channel on https://buildteamworld.slack.com/ ?

**Comment by dgassaway** [comment]
Hello! I'm open to having a channel but "supporting" it will be a very low priority for us. If you think it would add value to have it anyway, we can start one up.

**Comment by finnball** [comment]
Or at least join us on the Slack channel so if we ever discuss things about the API in general, you'll be there to comment :)

**Comment by dgassaway** [comment]
Yes, already in buildteamworld!

**Comment by buchgr** [comment]
Thanks @dgassaway

**Pull request merged**
